### PR TITLE
Add naman1901

### PR DESCRIPTION
**Pull request by naman1901**

### CODE REVIEW

**Comment by mbad0la** [comment]
@naman1901 we don't merge PRs from people who haven't contributed at ODIN yet. Please checkout our projects and get involved with us if you want to be a part of this community.

Thanks

**Comment by naman1901** [comment]
Wanted to be a part of HelloWorld, but as of now there isn't anything going on there. Do consider me when you plan to work on it.

**Comment by mbad0la** [comment]
@naman1901 what do you want to do on [HelloWorld](https://github.com/o-d-i-n/HelloWorld) project? Any preferences?

**Comment by naman1901** [comment]
Server side. It is a Django project, right?

**Comment by mbad0la** [comment]
Yup, the server side is django managed.  
@ab-decoded can you get @naman1901 involved with the server side?

**Comment by ab-decoded** [comment]
Sure, @naman1901. We have to start with login and then move to APIs. Looking forward to working with you!

**Comment by naman1901** [comment]
@ab-decoded Cool. I'll try to have a login system ready by the weekend.

**Comment by mbad0la** [comment]
@naman1901 please drop off an email at **you.can.contact.odin@gmail.com** so that we may get in touch with you and discuss the task or resolve any issues you might have.

**Comment by naman1901** [comment]
Accept this pull now?

**Pull request merged**
