### PR TITLE
Fetching team member images from their Github profile

### PR DESCRIPTION
**Pull request by shubhamkrm**
There's just one small issue : zerismo doesn't have his image as Github profile pic

### CODE REVIEW

**Comment by mbad0la** [comment]
Isn't there a way to automate the profile picture set in the github profile. Particularly, what happens when a person might change his github dp?

**Comment by shubhamkrm** [comment]
I think the changed dp should appear... Not sure though... I will have to test it

**Comment by mbad0la** [comment]
give it a try

**Comment by shubhamkrm** [comment]
When someone changes his/her DP, the changed DP will appear because the images are stored with unique user number/id of the person as filenames, so that no old images are kept in the storage. Hence, no matter how many times the DP is changed, the image referred to by the link is always the latest one, since the link used to retrieve the image is independent of the image itself.

**Comment by mbad0la** [comment]
Seems good enough, thanks a lot for resolving this issue!

**Pull request merged**
